name: Generate Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      # This is required to allow the Action to push to the repository
      contents: write
      
    # Corrected 'if' condition using the standard expression syntax
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install tfplugindocs
        run: go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest

      - name: Generate documentation
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          tfplugindocs generate --provider-name elevenlabs

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          # Add [ci skip] to the commit message to prevent the workflow from re-running
          git commit -m "docs: generate documentation [ci skip]"
          git push